### ISSUE TITLE
Determining out/in network coverage deductible

### ISSUE THREAD

**Issue by daxiang28** [pokitdok/pokitdok-nodejs#10]
Is there a field that I can look at to determine if a patient has a deductible for out/in network coverage. I have two plans that are returning similar deductible summaries, but have different coverages for out of network:

Anthem Blue Shield (has In-Network coverage with 0 deductible and OON coverage with $500 deductible):

```
  "deductible": {
      "individual": {
        "in_network": {
          "limit": {
            "amount": "0",
            "currency": "USD"
          },
          "applied": {
            "amount": "0.00",
            "currency": "USD"
          },
          "remaining": {
            "amount": "0",
            "currency": "USD"
          }
        },
        "out_of_network": {
          "limit": {
            "amount": "500",
            "currency": "USD"
          },
          "applied": {
            "amount": "0.00",
            "currency": "USD"
          },
          "remaining": {
            "amount": "500",
            "currency": "USD"
          }
        }
      }
    }
```

United Health (has In-Network coverage with 0 deductible and no OON coverage):

```
          "individual": {
            "in_network": {
              "limit": {
                "amount": "0",
                "currency": "USD"
              },
              "applied": {
                "amount": "0.00",
                "currency": "USD"
              },
              "remaining": {
                "amount": "0",
                "currency": "USD"
              }
            },
            "out_of_network": {
              "limit": {
                "amount": "0",
                "currency": "USD"
              },
              "applied": {
                "amount": "0.00",
                "currency": "USD"
              },
              "remaining": {
                "amount": "0",
                "currency": "USD"
              }
            }
          }
```

It seems like the 0 limit/ 0 applied/ 0 remaining could mean that the visit could be covered under their plan with purely a co-pay or is not covered at all by their plan. Could you safely say that looking at a co-pay plus the L/A/R co-pay amounts determines if there is OON coverage?

**Comment by denisekgosnell** [comment]
@daxiang28 Check out the table of keys in the json payload in our documentation: https://platform.pokitdok.com/documentation/v4/#eligibility

We pass on all of the information that we get from the payer.  The keys in the response payload of `coverage.deductibles` and `summary.deductible` will have that information, _if_ the trading partner returns it.  We are working to provide documentation on the likelihood that a trading parter will return a specific key in the eligibility response.
