### ISSUE TITLE
/eligibility/constants endpoint?

### ISSUE THREAD

**Issue by mkempinsky** [pokitdok/pokitdok-nodejs#14]
How can I hit this endpoint? 

/eligibility/constants

https://pokitdok.com/support/where-can-i-find-a-listing-of-health-care-service-type-codes-for-use-in-an-eligibility-request/

**Comment by corbinbs** [comment]
Hi @mkempinsky - there's an `apiRequest` routine 
https://github.com/pokitdok/pokitdok-nodejs/blob/master/index.js#L116 that the higher level convenience functions utilize to make API requests with the current access token.   The trading partners example is close to what you'd need to call https://github.com/pokitdok/pokitdok-nodejs/blob/master/index.js#L1453 except you'd replace the `path` with `/eligibility/constants`

Please let me know if that doesn't work for you for some reason

Thanks,

Brian

**Comment by mkempinsky** [comment]
@corbinbs Thank Brian, I think what I'm actually looking for is just adding service types to the request. 
However, I'm not seeing any additional information in the response. Do you know if this is possible through Pokitdok?

`service_types: ['health_benefit_plan_coverage', 'substance_abuse']`

**Comment by corbinbs** [comment]
Hi @mkempinsky - I dropped some information over at https://github.com/pokitdok/pokitdok-nodejs/issues/15#issuecomment-458279488

The short answer is `it is possible` but the results will `depend on the trading partner` (unfortunately).

Thanks,

Brian
