### ISSUE TITLE
Adding Service Type To /eligibility request

### ISSUE THREAD

**Issue by mkempinsky** [pokitdok/pokitdok-nodejs#15]
Trying to add additional service types to an /eligibility request but not seeing any additional information in the response.

For example: 

`service_types: ['health_benefit_plan_coverage', 'substance_abuse']`

**Comment by corbinbs** [comment]
Hi @mkempinsky  - you can submit additional `service_types` just like you've outlined.
If `service_types` is omitted in the request, it'll default to `['health_benefit_plan_coverage']` (aka - the basic eligibility check).    Unfortunately, it's up to the trading partner when it comes to the interpretation of the service types submitted on the request and how they'll respond to them.
Some partners only support the general `health_benefit_plan_coverage` inquiry and will respond the same way no matter what service type value(s) are submitted to them.   Some partners will return errors if you attempt to query using specific procedure codes as well (while other partners will respond differently when you're checking on a specific procedure).  `medicare_national` is an example where specific procedure information on the request will produce a different response:
```
"procedure_id": "G0120",
"procedure_id_qualifier": "hcpcs",
"trading_partner_id": "medicare_national"
```

Depending on the service type(s) you're targeting and the partner(s) you're checking, they may be including the information you need in different sections of the eligibility response even with the generic `health_benefit_plan_coverage`.    

Sorry for the "it depends" style response but there's just unfortunately a lot of variation across trading partners in the handling of that request parameter.  

Thanks,

Brian

**Comment by corbinbs** [comment]
no problem - happy to help.

I'll close out these issues.   Please open new items if you run across other areas you're not certain about or where you uncover some 🐛 s.

Thanks,

Brian
